### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by aleprovencio** [RealOrangeOne/theorangeone.net#84]
Hello,
I'm getting an error while subscribing at your blog's feed on nextcloud news.

It seems to be something about this post `Fix steam under linux with an iGPU`, here's the log:

```
...
"Message":"An exception occurred while executing 'INSERT INTO `oc_news_items`(`unread`,`url`,`guid`,`guid_hash`,`pub_date`,`last_modified`,`title`,`author`,`body`,`search_index`,`fingerprint`,`content_hash`,`feed_id`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)' with params [true, \"https:\\/\\/theorangeone.net\\/posts\\/steam-igpu-linux\\/\", \"https:\\/\\/theorangeone.net\\/posts\\/steam-igpu-linux\\/\"
...
```

**Comment by RealOrangeOne** [comment]
I couldn't reproduce this under Nextcloud 19.0.1, although the fact the page had a date of `0001-01-01` is a little suspect.

Fix should be out in 5 minutes or so, let me know if it fixes the issue!

**Comment by aleprovencio** [comment]
You got it, it works just fine now.
Very nice writing on `selfhosted`, BTW. :)
